name: global.website.name
highlighter: pygments
#url:
#    it: https://ftp.cryptoteam.it
#    en: https://ftp.cryptoteam.it

include: [.htaccess,__Analytics*]
exclude: [bin,README.md]

timezone: UTC

languages: ["it", "it", "en"]

description: global.website.description

excerpt_separator: N/A-------N/A... Workaround for https://github.com/mojombo/jekyll/issues/1401

### Disabled for now. Default is nice.
# permalink: :categories/:year-:month-:day-:title.html

# La navigazione da includere, ogni cosa inserita qui è
# una chiave per trovare la pagina corretta. Il nome e i titoli dei link
# sono presi da ciascuna pagina stessa, così come la relazione con la
# pagina a monte.

# Ogni nome deve essere unico e la pagina deve avere lo stesso nome.
# Controlla l'area all'interno del blocco --- e l'attributo del nome.
# Stesso nome, stessa pagina.
# Gli URL qui sono anche gli url costruiti di default.
# La personalizzazione lavora in modalità differente.

sitenavigation:
  - name: Servizi
    secondarynav:
        - name: Servizi
        - name: Protezione
  - name: Offerta
    secondarynav:
        - name: Offerta
        - name: Features
        - name: Licensing & Pricing
        - name: Documentation
        - name: Download
  - name: Company
    secondarynav:
        - name: Company
        - name: Management
        - name: Team
        - name: References
        - name: Press
  - name: News
  - name: Jobs
  - name: Contact
    secondarynav:
        - name: Contact
        - name: Privacy
  - name: :External
    title: Blog
    url: https://blog.xceptance.com/
